version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
